import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { toPoints } from "../src/analyze.ts";
import { renderReport, type OutputFormat } from "../src/render.ts";
import type { Meta, Sample } from "../src/types.ts";

interface Job {
  name: string;
  runner_name: string;
  steps: { number: number; name: string; conclusion: string | null; started_at: string | null; completed_at: string | null }[];
}

const [artifactsDir, jobsFile, outFile] = process.argv.slice(2);
const { jobs } = JSON.parse(readFileSync(jobsFile, "utf8")) as { jobs: Job[] };

const sections: string[] = [];
for (const job of jobs.sort((a, b) => a.name.localeCompare(b.name))) {
  const dir = join(artifactsDir, `gha-ekg-${job.runner_name.replace(/[^A-Za-z0-9._-]/g, "-")}`);
  if (!readdirSync(artifactsDir).includes(dir.split("/").pop()!)) continue;
  const meta = JSON.parse(readFileSync(join(dir, "meta.json"), "utf8")) as Meta;
  const samples = readFileSync(join(dir, "samples.jsonl"), "utf8").trim().split("\n").map((l) => JSON.parse(l) as Sample);
  const steps = job.steps
    .filter((s) => s.started_at && s.completed_at && s.conclusion !== "skipped")
    .map((s) => ({ number: s.number, name: s.name, start: Date.parse(s.started_at!), end: Date.parse(s.completed_at!) }));
  const format = (/, (ascii|mermaid)\)$/.exec(job.name)?.[1] ?? "ascii") as OutputFormat;
  sections.push(`# ${job.name}\n\n${renderReport(meta, toPoints(samples), steps, undefined, format)}`);
}

const intro = `<!-- Generated by scripts/render-demo.ts from a real demo workflow run. -->\n\nThese are the job summaries the action produced in the [demo workflow](https://github.com/ingarabr/gha-ekg/actions/workflows/demo.yml). Each job ran the same synthetic CPU, memory, disk and network workload.\n`;
writeFileSync(outFile, `${intro}\n${sections.join("\n\n---\n\n")}\n`);
console.log(`wrote ${outFile} (${sections.length} jobs)`);
